# use the official gcc image, based on debian
# can use verions as well, like gcc:5.2
# see https://hub.docker.com/_/gcc/
#image: gcc

stages:
  - build
  - test
#  - package

include:
# Debian
#  - local: .gitlab/ci/debian-with-deps.yml       # DinD, images with deps, moderate speed
# DISABLED DUE TO UNEXPECTED ERROR:
#Using Docker executor with image fedora:build ...
#Pulling docker image fedora:build ...
  - local: .gitlab/ci/debian.yml       # DinD, no images with deps, slower speed

# Fedora
  - local: .gitlab/ci/fedora.yml       # DinD, no images with deps, slower speed

# FreeBSD
#  - local: .gitlab/ci/freebsd-1-stage.yml       # Docker, fastest
  - local: .gitlab/ci/freebsd-3-stage.yml       # Docker, fastest

# AltLinux
#  - local: .gitlab/ci/altlinux.yml       # DinD, no images with deps, slower speed, turned off
# Fast Yandex mirror broken from time to time
# Slow Vendor repository is slow and inconvenient so

# Gentoo
#  - local: .gitlab/ci/gentoo.yml       # DinD, incomplete

# ArchLinux
#  - local: .gitlab/ci/archlinux.yml    # DinD, incomplete
