# use the official gcc image, based on debian
# can use verions as well, like gcc:5.2
# see https://hub.docker.com/_/gcc/
image: gcc

build:
  stage: build
  tags:
    - docker
  before_script:
    - apt update && apt -y install scons make libxml++2.6-dev
  script:
    - cd src && scons RELEASE=1 -j4
#  artifacts:
#    paths:
#      - mybinary
      # depending on your build setup it's most likely a good idea to cache outputs to reduce the build time
      # cache:
      #   paths:
      #     - "*.o"

# run tests using the binary built before
test:
  stage: test
  tags:
    - docker
  script:
    - make test
